# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ckIJoRfktiSnKrhUg8MrcWl1pU-UFjl-
"""

nota1 = 8.2
nota2 = 5.5

def verificar_aprovacao():
    media = calcular_media([nota1, nota2])

    if media >= 7:
        print('APROVADO')
    else:
        print('REPROVADO')

def calcular_media(notas):
    quantidade = len(notas)

    soma = 0
    for nota in notas:
        soma = soma + nota

    media = soma / quantidade

    return media

verificar_aprovacao()

frutas = ['Banana', 'Laranja', 'Morango', 'Abacaxi']
guloseimas = ['Biscoito', 'Chocolate', 'Fini']
comidas = ['Macarrão', 'Carne', 'Frango', 'Feijão']
bebidas = ['Água', 'Refrigerante', 'Suco']

categorias = ['Frutas', 'Guloseimas', 'Comidas', 'Bebidas']
compras = [frutas, guloseimas, comidas, bebidas]

for indice, categoria in enumerate(categorias):
    print('Você precisa comprar', len(compras[indice]), categoria+':')
    for compra in compras[indice]:
        print('-', compra)

animais = []

animal = input('Digite o nome dos seus animais de estimação ou digite 0 se não tiver: ')

while animal != '0':
        especie = input('Digite a espécie desse animal: ')
        animais.append([animal, especie])
        animal = input('Se tiver mais animais, digite o nome. Ou digite 0 se nao tiver: ')
if len(animais) == 0:
    print('\n\nVocê não tem animais')
else:
    print('\n\nVocê tem os seguintes animais: ')
    for animal in animais:
        print('-Nome:', animal[0], '| Espécie:', animal[1])

